### ISSUE TITLE
JOSS Review - examples/encoding_examples.py crashes

### ISSUE THREAD

**Issue by mbsuraj** [scikit-learn-contrib/category_encoders#486]
This issue is w.r.t. submission made to JOSS here - https://github.com/openjournals/joss-reviews/issues/10645#issuecomment-4762332450

The example script encoding_examples.py fails immediately when it is run with the package's own declared dependencies (scikit-learn>=1.6.0 as per pyproject.toml).

To reproduce this error, you can do:
```
cd examples
python encoding_examples.py
```

Specific error I get is:
TypeError: LogisticRegression.__init__() got an unexpected keyword argument 'multi_class'

As far I went through the code, it is because of line 62 in the example, where multi_class='auto' was provided as a parameter; but this parameter was deprecated in scikit-learn 1.7 and removed in 1.9. Given that the package declares scikit-learn >= 1.6.0 as a dependency, any fresh install with get sklearn 1.9+ and hit this error.

Suggested fix:
Remove the multi_class argument in the example

```
clf = linear_model.LogisticRegression(
    solver='lbfgs', max_iter=200, random_state=0
)
```

Also update the comment at the top of the file which says "Tested to work with scikit-learn 0.20.2" - it could mislead someone trying to learn given the current dependency requirements.
